### ISSUE TITLE
Error building with Node +Nest

### ISSUE THREAD

**Issue by fabianmedina09** [optilude/xlsx-template#131]
Hi,

I run the next build command: `rimraf dist && nest build `

And this is the result 
![image](https://user-images.githubusercontent.com/18604685/100281276-9ede2f00-2f37-11eb-9375-f0f52e732413.png)

This is happening in version 1.3.0 that adds this:
Added support for optional moving of the images together with table

Solved working with versión 1.2.0, but maybe someone needs support to the new features

**Comment by gotama** [comment]
Ive got the same issue, Typescript wants you to use number.  If I get time to do this ill submit a PR for changing int to number, However for now im going to downgrade to 1.2.0

@fabianmedina09  could you change the title to have "Cannot find name 'int'."  then atleast other people can find this issue as well

**Comment by y-hsgw** [comment]
@kant2002
I think this issue has already been resolved, so it should be okay to close it.
